# Generated by Django 3.2.6 on 2021-09-27 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='autos',
            field=models.ManyToManyField(to='users.Auto', verbose_name='los carros del usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='apellidos',
            field=models.CharField(max_length=100, verbose_name='los apellidos del usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombres',
            field=models.CharField(max_length=100, verbose_name='los nombres del usuario'),
        ),
        migrations.AlterField(
            model_name='website',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
